### DISCUSSION TITLE
Today details grid Phasenleistung

### DISCUSSION THREAD

**Discussion by endurance1968** [ha-puzzles/evcc-grafana-dashboards#155] [General]
Mich wundert es, dass die leistung pro phase fehlt (grid)
![grafik](https://github.com/user-attachments/assets/4db65079-5326-4c4a-bd64-e17c1cd4da98)

Laut victron template müsste es eigentlich übertragen werden:
[victron template](https://github.com/evcc-io/evcc/blob/master/templates/definition/meter/victron-energy.yaml)
```
  type: custom
  {{- if eq .usage "grid" }}
  power:
    source: calc
    add:
    - source: modbus
      uri: {{ .host }}:{{ .port }}
      id: 100 # com.victronenergy.system
      register:
        address: 820 # L1 grid power
        type: input
        decode: int16
    - source: modbus
      uri: {{ .host }}:{{ .port }}
      id: 100 # com.victronenergy.system
      register:
        address: 821 # L2 grid power
        type: input
        decode: int16
    - source: modbus
      uri: {{ .host }}:{{ .port }}
      id: 100 # com.victronenergy.system
      register:
        address: 822 # L3 grid power
        type: input
        decode: int16
```

**Comment by cschlipf** [comment]
Nein, schau Dir das Meter nochmal an. Es ist vom Typ calc und nutzt die Add Funktion um die einzelnen Phasen zu einem Wert zusammenzufassen.

**Reply by endurance1968** [reply]
Das calc hab ich gar nicht gesehen, d.h. wenn ich das Grid Meter direct einbinde (mit allen Werten) und nicht über das template , sollte es gehen. 
![grafik](https://github.com/user-attachments/assets/2c67bad1-361d-4509-ad69-c91079adc83e)

**Reply by endurance1968** [reply]
Hmm ich finde keine Möglichkeit die Leistung pro Phase an evcc zu übergeben. sagt immer will ne map bekommt aber einen slice (auflistung nehme ich mal an).   
`'Power' expected a map, got 'slice'`

Das war mein Versuch
```
- type: custom
  name: mygrid
  power:
    - source: mqtt
      topic: haus/grid/leistung/l1
    - source: mqtt
      topic: haus/grid/leistung/l2
    - source: mqtt
      topic: haus/grid/leistung/l3
  currents:
    - source: mqtt
      topic: haus/grid/strom/l1
    - source: mqtt
      topic: haus/grid/strom/l2
    - source: mqtt
      topic: haus/grid/strom/l3
```

**Comment by cschlipf** [comment]
Da muss Dir jemand von EVCC helfen.

OKrause ***@***.***> schrieb am Mo., 31. März 2025, 22:56:

**Reply by endurance1968** [reply]
Anfrage ist gestellt, aber was nutzt Ihr um die Leistung zur Phase zu erhalten. Sprich was für ein template wo ich spickeln kann.

**Comment by endurance1968** [comment]
Lösung ein kleines s trotzde muss das power auch da sein.  Ich cleverle dacht nat. entweder oder.

```
- type: custom
  name: grid-meter
  power:
    source: mqtt
    topic: haus/grid/power/total
    timeout: 10s
  powers:
    - source: mqtt
      topic: haus/grid/power/l1
      timeout: 10s
    - source: mqtt
      topic: haus/grid/power/l2
      timeout: 10s
    - source: mqtt
      topic: haus/grid/power/l3
      timeout: 10s
  currents:
    - source: mqtt
      topic: haus/grid/strom/l1
      timeout: 15s
    - source: mqtt
      topic: haus/grid/strom/l2
      timeout: 15s
    - source: mqtt
      topic: haus/grid/strom/l3
      timeout: 15s
  voltages:
    - source: mqtt
      topic: haus/grid/spannung/l1
      timeout: 15s
    - source: mqtt
      topic: haus/grid/spannung/l2
      timeout: 15s
    - source: mqtt
      topic: haus/grid/spannung/l3
      timeout: 15s
  energy:
    source: mqtt
    topic: haus/grid/energy/netzbezug
```

Die ersten Werte sind auch schon da
![grafik](https://github.com/user-attachments/assets/833fd5ab-d933-488d-bade-d11c83e8f97c)
