### ISSUE TITLE
0.5.3 issues

### ISSUE THREAD

**Issue by endurance1968** [ha-puzzles/evcc-grafana-dashboards#128]
Not referenced Variables could be removed? Looks like Grafana is wrong here after checking the panels - just for completelness here: In Daily Dashboard
![Image](https://github.com/user-attachments/assets/9e346ed5-df98-4702-8342-ee4f894edf8a)

Max PV Power Threshold in Monthly dashboard should be a variable
![Image](https://github.com/user-attachments/assets/9436570c-bbcc-46e7-bf44-ec15f0ad99cd)

Auch im Monatsdashbaord
![Image](https://github.com/user-attachments/assets/948730e1-d8b7-40ba-a2fd-e48ff524e266)
Autarkie schaut nach rechts raus - ist mir eigentlich nur gestern störend aufgefallen (nur ein Tag vom Monat vorhanden)

Speicher Effizienz scheint mir doch arg hoch im Yearly Dashboard.
![Image](https://github.com/user-attachments/assets/e65190f5-be59-4f9b-9bb4-1d982b5af721)
Laut Victron habe ich 956kwh to battery und 807kwh from battery was ca. 84% entspricht. Meiner Erfahrung nach für AC gekoppeltes System normal.

Ah und schon wieder denglish :)

**Comment by cschlipf** [comment]
Not referenced Variables - wird falsch von Grafana reported. Beide Variablen werden in Library Panels referenziert.

MAX Power Threshold: Ja, leider erlaubt Grafana hier nur zahlen, keine Variablen.

Monatsdashboard ist nir bekannt. Noch keine Lösung.

Bei der Batterie. Werden hier exakt dieselben Register ausgelesen und an derselben Stelle gemessen? Das macht einen großen Unterschied.

**Comment by endurance1968** [comment]
Also EVCC bekommt PV, Batterie und grid von Victron. Victron bekommt nur die Ladepunkt von EVCC.
Von daher sollten es dieselben Messpunkte sein. Ob EVCC die Werte richtig hat keine Ahnung, oder kann man Batterieladung/entladung auch irgendwo direkt in EVCC sehen?

```
meters:
- type: template
  template: victron-energy
  usage: grid
  host: 192.168.1.71
  port: 502
  name: victron-grid
  meterid: 40
- type: template
  template: victron-energy
  usage: pv
  host: 192.168.1.71
  port: 502
  name: victron-pv
- type: template
  template: victron-energy
  usage: battery
  host: 192.168.1.71
  port: 502
  name: victron-battery
  minsoc: 15
  maxsoc: 85
```
