### ISSUE TITLE
Heizlüfter im Daily Dashboard

### ISSUE THREAD

**Issue by endurance1968** [ha-puzzles/evcc-grafana-dashboards#179]
![Image](https://github.com/user-attachments/assets/c55d9667-1811-4ccc-8fc1-5706919dc0f9)

Die aktuelle Leistung entspricht meiner Wärmepumpe.

Aber im Kurvenchart ist es irgendetwas - passt am ehesten zum Gesamthausverbrauch aber auch nicht so richtig. Hmm ich denke das ist in der Kurve vermutlich mein Unterverteiler-circuit, an dem hängt 3/4 vom Haus - das würde passen.

scheint extPower zu sein in den Abfragen. Macht bei mir nicht wirklich Sinn das extra anzuzeigen. Ein Heizlüfter ist es aber in keinem Fall. Es könnten auch mehrere Circuits da sein - ich habe auch noch weitere nur noch nicht in EVCC eingebunden.

```
circuits:
  - name: main # unique name, used as reference, e.g. as parent in other circuits
    title: VNB-Netz
    maxcurrent: 32.5 # Fuse has 35A but to be on the safe side take 32.5A only
    maxpower: 22230 # min voltage seen so far 228V
    meter: grid-meter
#    meter: mygrid
    parent: # no parent, this is the root circuit
#  - name: lpc
#    title: Limitation of Power Consumption
#    parent: main
  - name: carport-ecke # unique name, used as reference, e.g. to associate loadpoints
    title: Carport-Ecke # used in the UI
    maxcurrent: 32
    maxpower: 21888 # min voltage seen so far 228V
    parent: main # parent to the main circuit
  - name: carport-treppe # unique name, used as reference, e.g. to associate loadpoints
    title: Carport-Treppe # used in the UI
    maxcurrent: 16
    maxpower: 10944 # min voltage seen so far 228V
    parent: main
  - name: haus-verteiler-stromkreis # unique name, used as reference, e.g. to associate loadpoints
    title: Haus-Verteiler # used in the UI
    maxcurrent: 32
    maxpower: 20000 #
    parent: main
    meter: haus-verteiler-ug-meter
  - name: waermepumpe-stromkreis # unique name, used as reference, e.g. to associate loadpoints
    title: Waermepumpe # used in the UI
    maxcurrent: 16
    maxpower: 11520 # typically we have ~240V therefor the power is pretty high
    parent: haus-verteiler-stromkreis
    meter: waermepumpen-meter
```

```
meters:
#- type: template
#  template: victron-energy
#  usage: grid
#  host: 192.168.1.71
#  port: 502
#  name: victron-grid
#  meterid: 40
- type: custom
  name: grid-meter
  power:
    source: mqtt
    topic: haus/grid/power/total
    timeout: 10s
  powers:
    - source: mqtt
      topic: haus/grid/power/l1
      timeout: 10s
    - source: mqtt
      topic: haus/grid/power/l2
      timeout: 10s
    - source: mqtt
      topic: haus/grid/power/l3
      timeout: 10s
  currents:
    - source: mqtt
      topic: haus/grid/strom/l1
      timeout: 15s
    - source: mqtt
      topic: haus/grid/strom/l2
      timeout: 15s
    - source: mqtt
      topic: haus/grid/strom/l3
      timeout: 15s
  voltages:
    - source: mqtt
      topic: haus/grid/spannung/l1
      timeout: 15s
    - source: mqtt
      topic: haus/grid/spannung/l2
      timeout: 15s
    - source: mqtt
      topic: haus/grid/spannung/l3
      timeout: 15s
  energy:
    source: mqtt
    topic: haus/grid/energy/netzbezug
- type: template
  template: victron-energy
  usage: pv
  host: 192.168.1.71
  port: 502
  name: victron-pv
- type: template
  template: victron-energy
  usage: battery
  host: 192.168.1.71
  port: 502
  name: victron-battery
  minsoc: 30
  maxsoc: 85
- type: custom
  name: haus-verteiler-ug-meter
  power:
    source: mqtt
    topic: haus/verteiler/haus/leistung
    timeout: 30s # don't accept values older than timeout
  currents:
    - source: mqtt
      topic: haus/verteiler/haus/strom/l1
    - source: mqtt
      topic: haus/verteiler/haus/strom/l2
    - source: mqtt
      topic: haus/verteiler/haus/strom/l3
- type: custom
  name: waermepumpen-meter
  energy:
    source: mqtt
    topic: haus/wp/energie
    timeout: 45s
  power:
    source: mqtt
    topic: haus/wp/leistung
    timeout: 45s # don't accept values older than timeout
  currents:
   - source: mqtt
      topic: haus/wp/strom/l1
    - source: mqtt
      topic: haus/wp/strom/l2
    - source: mqtt
      topic: haus/wp/strom/l3
```
